(progn
  (defun org-remember-one-time-undo-hook ()
    (remove-hook 'after-save-hook 'org-remember-one-time-hook)
    (remove-hook 'remember-mode-hook 'delete-other-windows)
    (define-key org-remember-mode-map [(control c)(control k)] 'org-remember-kill))
  (defun org-remember-one-time-hook ()
    (org-remember-one-time-undo-hook)
    (delete-frame))
  (defun org-remember-kill-one-time-hook ()
    (interactive)
    (org-remember-one-time-undo-hook)
    (org-remember-kill)
    (delete-frame))
  (define-key org-remember-mode-map [(control c)(control k)] 'org-remember-kill-one-time-hook)
  (add-hook 'after-save-hook 'org-remember-one-time-hook)
  (add-hook 'remember-mode-hook 'delete-other-windows)
  (org-remember)
  )
