* [[http://www.emacswiki.org/emacs/ActionScriptMode][actionscript.el]]

* [[http://www.gentei.org/~yuuji/software/][revive.el]]

=wget http://www.gentei.org/~yuuji/software/revive.el=

* [[http://www.emacswiki.org/emacs/MatlabMode][matlab.el]]

http://sourceforge.net/scm/?type=cvs&group_id=154105

* [[http://www.gentei.org/~yuuji/software/][windows.el]]

=wget http://www.gentei.org/~yuuji/software/windows.el=

* [[http://tromey.com/elpa/][elpa]] package.el

  eval this:
#+BEGIN_SRC emacs-lisp
  (let ((buffer (url-retrieve-synchronously
           "http://tromey.com/elpa/package-install.el")))
  (save-excursion
    (set-buffer buffer)
    (goto-char (point-min))
    (re-search-forward "^$" nil 'move)
    (eval-region (point) (point-max))
    (kill-buffer (current-buffer))))
#+END_SRC

* [[http://julien.danjou.info/rainbow-mode.html][rainbow-mode.el]]

  =git clone git://git.naquadah.org/rainbow.git=

* [[http://www.nongnu.org/color-theme/][color-theme]]

  download from [[http://download.savannah.gnu.org/releases/color-theme/]] or see [[http://www.emacswiki.org/emacs/ColorTheme][color-theme wiki]]

* [[http://code.google.com/p/yasnippet/][yasnippet (non bundle)]]

yasnippet-bundle makes you unable to add your own templates

=svn checkout http://yasnippet.googlecode.com/svn/trunk/ yasnippet-read-only=

** [[http://github.com/cofi/yasnippet-org-mode.git][cofi's fork of yasnippet-orgmode]]

git clone http://github.com/cofi/yasnippet-org-mode.git org-mode

* wanderlust

** APEL, FLIM, SEMI

=wget http://kanji.zinbun.kyoto-u.ac.jp/~tomo/lemi/dist/apel/apel-10.8.tar.gz=

=wget http://www.kanji.zinbun.kyoto-u.ac.jp/~tomo/comp/emacsen/lisp/flim/flim-1.14/flim-1.14.9.tar.gz=

=wget http://kanji.zinbun.kyoto-u.ac.jp/~tomo/lemi/dist/semi/semi-1.14-for-flim-1.14/semi-1.14.6.tar.gz=

installation is tricky

install APEL first

then FLIM

on OSX running make calls the default emacs, and it tries to use a version-specific folder that isn't where the graphical emacs reads
also, if make cannot find "install" it is because APEL isn't in the load-path. you'll have to edit FLIM-CFG and make sure it's there

then SEMI
both APEL and FLIM need to be in the load-path in SEMI-CFG

** Cannot open: elmo-network-initialize-session

   http://d.hatena.ne.jp/yamdan/20090430/1241105044

久しぶりに wanderlust で gmail を読もうとしたら、

Cannot open: elmo-network-initialize-session

なんてエラーが表示され、メールが取得できなくなってしまっていた。

色々調べる内に、原因と対策が判明したので、以下に記録する。

以下のページがとても役に立った。感謝します。

[riwablo: さくらインターネットとimapとopensslとwl]

http://riwablo.blogspot.com/2008/04/imapopensslwl.html

*** 原因
  
#+begin_quote 
imap.gmail.com へ SSL/TLS で接続する際、
imap.gmail.com のサーバ証明書の検証に失敗するため、
wanderlust (elmo) がセッション確立の途中でエラーを吐いて終了する。
サーバ証明書の検証に失敗してしまうのは、
証明書の発行者 (issuer) である "Equifax Secure Certificate Agency" のルート証明書が、
openssl から利用できていないため。
#+end_quote

*** 対策(1) (推奨)

**** openssl 用証明書ストア (ディレクトリ) の準備

openssl が証明書を読みにいくディレクトリを用意する。

#+begin_quote 
bash-3.2$ mkdir -m 744 -p ~/.w3/certs
#+end_quote

**** ルート証明書の取得

openssl s_client で imap.gmail.com:993 へ接続してみると、
imap.gmail.com のサーバ証明書は Equifax Secure Certificate Agency によって
発行されていることが分かる。

#+begin_quote
bash-3.2$ openssl s_client -host imap.gmail.com -port 993
CONNECTED(00000006)
depth=1 /C=US/O=Google Inc/CN=Google Internet Authority
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=imap.gmail.com
i:/C=US/O=Google Inc/CN=Google Internet Authority
1 s:/C=US/O=Google Inc/CN=Google Internet Authority
i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
(以下略)
#+end_quote

Equifax Secure Certificate Agency のルート証明書は、
firefox の証明書ストアなどに入っているので、そこから取得する。
環境設定→詳細→暗号化→証明書を表示...
で表示される証明書のリストから

"Equifax" の "Equifax Secure CA" をクリックし、

"書き出す..." ボタンをクリック。
ファイル形式は PEM を選択し、

上で作った ~/.w3/certs ディレクトリへ保存する。

**** シンボリックリンクの生成

openssl が適切に証明書を選択できるように、
subject のハッシュ値に ".0" を付加したシンボリックリンクを作る。
といってもやるのはコマンド c_rehash を実行するだけ。

#+begin_quote
bash-3.2$ c_rehash ~/.w3/certs
#+end_quote

これで ~/.w3/certs 内に証明書へのシンボリックリンクが作られる。

#+begin_quote 
bash-3.2$ ls -l ~/.w3/certs
total 16
lrwxr-xr-x  1 yamdan  staff    19  4  7 00:09 594f1775.0 -> EquifaxSecureCA.pem
-rw-r--r--@ 1 yamdan  staff  1162  4  7 00:06 EquifaxSecureCA.pem
#+end_quote

**** .wl の編集

.wl へ以下を追記する。

#+BEGIN_SRC emacs-lisp
;; SSL/TLS 用証明書ストアのパス
(setq ssl-certificate-directory "/Users/yamdan/.w3/certs")
#+END_SRC

ここでは必ず絶対パスを指定すること。

"~/.w3/certs" のような指定をするとディレクトリの読み込みに失敗する。

(ssl.el の内部では、openssl の実行に start-process-shell-command ではなく start-process を利用しており、シェルによる引数の展開 "~/.w3/certs" --> "/Users/yamdan/.w3/certs" が行われないため)

**** 完了

以上で imap.gmail.com への接続に成功するはず。

.wl は最終的に以下のようになる。

#+BEGIN_SRC emacs-lisp
;; IMAP サーバの設定
(setq elmo-imap4-default-server "imap.gmail.com")
(setq elmo-imap4-default-user "xxxxxxxxxxxx@gmail.com")
(setq elmo-imap4-default-authenticate-type 'clear)
(setq elmo-imap4-default-port '993)
(setq elmo-imap4-default-stream-type 'ssl)
(setq elmo-imap4-use-modified-utf7 t)

;; SMTP サーバの設定
(setq wl-smtp-connection-type 'starttls)
(setq wl-smtp-posting-port 587)
(setq wl-smtp-authenticate-type "plain")
(setq wl-smtp-posting-user "xxxxxxxxxxxxx")
(setq wl-smtp-posting-server "smtp.gmail.com")

;; SSL/TLS 用証明書ストアのパス
(setq ssl-certificate-directory "/Users/yamdan/.w3/certs")
#+END_SRC




* emacs-w3m (required to render html-formatted emails in wl)

  easiest way...
  port install w3m
  port install emacs-w3m

  might need to add these lines:
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "/opt/local/share/emacs/site-lisp/w3m")
  (setq w3m-command "/opt/local/bin/w3m")
  (require 'w3m-load)
  (require 'w3m-e21)
  (provide 'w3m-e23)
  (require 'mime-w3m)
#+END_SRC

* updated org-mode (>= 7.01h)

** use git repo:

   =git clone git://repo.or.cz/org-mode.git=
